DATABASE_URL = "postgresql://postgres:1234@localhost:5432/Algotrader"
DATABASE_URL_RENDER=postgresql://cryptopilot:h50BgaRYIGJWLkpoLni1OEuYjkEmMLwM@dpg-d22nnfh5pdvs7396b830-a.oregon-postgres.render.com/algotrader_db_3o6k
